apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: b-helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy:
    automated: {}